image: golang:1.12-alpine

stages:
  - test
  - build
  - build-image

.before_script_defaults: &before_script_defaults
  before_script:
    - mkdir -p /go/src/github.com/joshfng /go/src/_/builds
    - cp -r $CI_PROJECT_DIR /go/src/github.com/joshfng/relay
    - ln -s /go/src/github.com/joshfng /go/src/_/builds/joshfng
    - apk --update add make git

build:
  <<: *before_script_defaults
  stage: build
  script:
    - make

build-image:
  <<: *before_script_defaults
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/joshfng/relay/relay:latest -f Dockerfile.relay .
    - docker push $CI_REGISTRY/joshfng/relay/relay:latest
# unit_tests:
#   stage: test
#   script:
#     - make test
#
# race_detector:
#   stage: test
#   script:
#     - make race
#
# memory_sanitizer:
#   stage: test
#   script:
#     - make msan
#
# code_coverage:
#   stage: test
#   script:
#     - make coverage
#
# code_coverage_report:
#   stage: test
#   script:
#     - make coverhtml
#   only:
#   - master
#
# lint_code:
#   stage: test
#   script:
#     - make lint
