version: "3"

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    # command: ["redis-server", "--bind", "0.0.0.0"]

  proxy:
    ports:
      - "1935:1935"
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    depends_on:
      - relay

  relay:
    container_name: relay
    build:
      context: .
      dockerfile: Dockerfile.relay
    env_file: .env
    restart: on-failure
    links:
      - redis
    depends_on:
      - redis
