FROM golang:1.12-alpine

RUN apk --update add git ffmpeg htop bash make

WORKDIR /go/src/github.com/joshfng/relay

COPY . .

RUN go get .
RUN go build -o relay *.go

EXPOSE 1935

STOPSIGNAL SIGTERM

ENTRYPOINT ["./relay"]
