version: "3"

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # proxy:
  #   ports:
  #     - "1935:1935"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.proxy
  #   container_name: proxy
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - relay

  relay:
    container_name: relay
    ports:
      - "1935:1935"
    build:
      context: .
      dockerfile: Dockerfile.relay
    env_file: .env
    stop_grace_period: 30s
    links:
      - redis
    depends_on:
      - redis
