version: "3.7"

services:
  redis:
    image: redis:5-alpine
    expose:
      - "6379"
    restart: always
    ports:
      - "6379:6379"

  # proxy:
  #   build:
  #     context: .
  #     dockerfile: proxy.Dockerfile
  #   container_name: proxy
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - relay
  #   expose:
  #     - "1935"
  #   restart: always
  #   ports:
  #     - "1935:1935"

  relay:
    build:
      context: .
      dockerfile: relay.Dockerfile
    container_name: relay
    env_file: .env
    stop_grace_period: 30s
    depends_on:
      - redis
    expose:
      - "1935"
    ports:
      - "1935:1935"
    restart: always
    volumes:
      - ./:/go/src/github.com/joshfng/relay
