version: '3'

services:
  proxy:
    ports:
      - "1935:1935"
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - relay

  relay:
    container_name: relay
    build:
      context: .
      dockerfile: Dockerfile.relay
    env_file: .env
