FROM golang:1.12-alpine

RUN apk update
RUN apk add git ffmpeg htop bash

WORKDIR /go/src/github.com/joshfng/relay

COPY . .

RUN go get .
RUN go build -o relay *.go

EXPOSE 1935

STOPSIGNAL SIGTERM

ENTRYPOINT ["./relay"]
