FROM golang:1.12-alpine AS builder

RUN apk --update add git bash make

WORKDIR /go/src/github.com/joshfng/relay

COPY . .

RUN go get .
RUN go build -o relay *.go

FROM alpine

RUN apk --update add ffmpeg htop tini

COPY --from=builder /go/src/github.com/joshfng/relay/relay /relay

EXPOSE 1935

STOPSIGNAL SIGTERM

ENTRYPOINT ["/sbin/tini", "--", "./relay"]
